---
{{- $githubName := .Values.vaultCommon.github.name }}
{{- $githubType := .Values.vaultCommon.github.type }}
{{- $githubKeys := .Values.vaultCommon.github.keys }}
{{- $githubPath := .Values.vaultCommon.github.path }}
apiVersion: spacecontroller.infoblox-cto.github.com/v1alpha1
kind: Space
metadata:
  labels:
    app: {{ template "teleport.name" . }}
  name: {{ $githubName }}
  namespace: {{ .Release.Namespace }}
spec:
  path: {{ tpl $githubPath . }}
  secretName: {{ $githubName }}
  secrets:
    {{- range $githubKeys }}
    {{ . }}: VAULT
    {{- end }}
  type: {{ $githubType }}
