---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "teleport.name" . }}
  namespace: {{ template "teleport.namespace" . }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
data:
  teleport.yaml: |
    teleport:
      log:
        output: stderr
        severity: DEBUG
      data_dir: /var/lib/teleport
      auth_servers:
      - {{ template "teleport.name" . }}-{{ .Values.serviceInternalName }}.{{ template "teleport.namespace" . }}.svc.cluster.local:3025
      #- {{ tpl .Values.appDomain . }}:3025
      storage:
        region: {{ .Values.region }}
        audit_sessions_uri: {{ tpl .Values.config.auditSessionsUri . | quote }}
        #Dynamo
        type: dynamodb
        table_name: {{ template "teleport.name" . }}-{{ .Values.env }}
        audit_events_uri:
        - dynamodb://{{ template "teleport.name" . }}-events-{{ .Values.env }}
    auth_service:
      enabled: {{ .Values.config.auth_service.enabled }}
      #session_recording: "off"
      authentication:
        second_factor: off
        type: github
      cluster_name: {{ required "Cluster name is required" .Values.env }}
      listen_addr: 0.0.0.0:3025
      #public_addr: "{{ tpl .Values.appDomain . }}:3025"
      client_idle_timeout: 1h
    ssh_service:
      enabled: {{ .Values.config.ssh_service.enabled }}
      #public_addr: "{{ tpl .Values.appDomain . }}:3022"
      listen_addr: 0.0.0.0:3022
    proxy_service:
      enabled: {{ .Values.config.proxy_service.enabled }}
      listen_addr: 0.0.0.0:3023
      tunnel_listen_addr: 0.0.0.0:3024
      web_listen_addr: 0.0.0.0:3080
      public_addr: "{{ tpl .Values.appDomain . }}:3080"
      #ssh_public_addr: "{{ tpl .Values.appDomain . }}:3023"
      tunnel_public_addr: "{{ tpl .Values.appDomain . }}:3024"
      https_key_file: /var/lib/certs/tls.key
      https_cert_file: /var/lib/certs/tls.crt
{{- if .Values.github }}
  github.yaml: |
    kind: github
    version: v3
    metadata:
      name: github
    spec:
      client_id: {{ .Values.github.clientID }}
      client_secret: {{ .Values.github.clientSecret }}
      display: {{ .Values.github.display }}
      redirect_url: "https://{{ tpl .Values.appDomain . }}:3080/v1/webapi/github/callback"
      teams_to_logins:
  {{- range $teams := .Values.github.teams_to_logins }}
      - kubernetes_groups:
        {{- range $teams.kubernetesGroups }}
        - {{ . }}
        {{- end }}
        logins:
        {{- range $teams.logins }}
        - {{ . }}
        {{- end }}
        organization: {{ tpl ($teams.organization) $ }}
        team: {{ tpl ($teams.team) $ }}

  {{- end }}
  {{- if .Values.role }}
  {{- end }}
  role.yaml: |
    kind: "role"
    version: "v3"
    metadata:
      name: {{ .Values.role.userName }}
    spec:
      options:
        max_session_ttl: "90h0m0s"
      allow:
        logins: [ {{ .Values.role.userName }} ]
        node_labels:
          access: {{ .Values.role.nodeLabel }}
{{- end }}
---
